Feed:
  Url: https://news.ycombinator.com/rss

Mercury:
  ApiUrl: https://mercury.postlight.com/parser
  ApiKey: FROM.ASP.NET
  TestUrl: https://trackchanges.postlight.com/building-awesome-cms-f034344d8ed

Blacklist:
  - .*phone.*
  - .*twilio.*
  - .*nytimes\..*